version: '3.8'

services:
  # CloudPulse Agent
  cloudpulse-agent:
    build:
      context: ../agent
      dockerfile: Dockerfile
    image: cloudpulse-agent:latest
    container_name: cloudpulse-agent
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - NODE_ID=${NODE_ID:-node-1}
      - PORT=${AGENT_PORT:-8080}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    networks:
      - cloudpulse-network

  # CloudPulse ML Service
  cloudpulse-ml:
    build:
      context: ../ml-models
      dockerfile: Dockerfile
    image: cloudpulse-ml:latest
    container_name: cloudpulse-ml
    ports:
      - "5001:5000"
    env_file:
      - ../.env
    environment:
      - AGENT_ENDPOINTS=${AGENT_ENDPOINTS:-http://cloudpulse-agent:8080}
      - MODEL_SAVE_PATH=${MODEL_SAVE_PATH:-/app/models}
      - FORECAST_INTERVAL_MINUTES=${FORECAST_INTERVAL_MINUTES:-5}
      - MODEL_RETRAIN_INTERVAL_HOURS=${MODEL_RETRAIN_INTERVAL_HOURS:-24}
      - LSTM_SEQUENCE_LENGTH=${LSTM_SEQUENCE_LENGTH:-60}
      - LSTM_HIDDEN_UNITS=${LSTM_HIDDEN_UNITS:-50}
      - LSTM_DROPOUT_RATE=${LSTM_DROPOUT_RATE:-0.2}
      - LSTM_EPOCHS=${LSTM_EPOCHS:-100}
      - LSTM_BATCH_SIZE=${LSTM_BATCH_SIZE:-32}
      - PROPHET_GROWTH_MODEL=${PROPHET_GROWTH_MODEL:-linear}
      - PROPHET_SEASONALITY_MODE=${PROPHET_SEASONALITY_MODE:-multiplicative}
    volumes:
      - ml-models:/app/models
    restart: unless-stopped
    depends_on:
      - cloudpulse-agent
    networks:
      - cloudpulse-network

  # CloudPulse Dashboard
  cloudpulse-dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    image: cloudpulse-dashboard:latest
    container_name: cloudpulse-dashboard
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - PORT=${DASHBOARD_PORT:-3000}
      - AGENT_ENDPOINTS=${AGENT_ENDPOINTS:-http://cloudpulse-agent:8080}
      - ML_SERVICE_URL=${ML_SERVICE_URL:-http://cloudpulse-ml:5000}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_FORECASTING=${ENABLE_FORECASTING:-true}
      - ENABLE_ALERTING=${ENABLE_ALERTING:-true}
      - ENABLE_AUTO_SCALING=${ENABLE_AUTO_SCALING:-true}
    volumes:
      - dashboard-logs:/app/logs
    restart: unless-stopped
    depends_on:
      - cloudpulse-agent
      - cloudpulse-ml
    networks:
      - cloudpulse-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: cloudpulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - cloudpulse-network

volumes:
  ml-models:
  dashboard-logs:
  redis-data:

networks:
  cloudpulse-network:
    driver: bridge
